	port="8080"
	[user]
		root = "root"
		password = "1234"
		group = "admin_group"
	[jwt]
		realm="atlasmap"
		key="salta-atad-6221"
		timeOut="720h"
		timeMax="72000h"
		identityKey="id"
		lookup="header:Authorization, query:token, cookie:Token"
		headName="Bearer"

	[attempts]
		ip = 50
		user = 7
		expiration = "-5m"

	[db]
		host     = "127.0.0.1"
		port     = "5432"
		user     = "atlas"
		password = "atlas"
		name   = "atlas"
		
	[buffers]
		prefix = "block_"
		suffix = "_buffers"
		scales = "buffer_scales"
		scaleType = "网点类型"
		blocks = "block_lines"
		radius = 300


	[models]
		[models.m2]
		const = 69
		weights = "m2_weights"

		[models.m4]
		weights = "m4_weights"
		scales = "m4_scales"

		[models.m5]
		field = "银行类别"
		values = ["中国银行","建设银行","工商银行","农业银行","兰州农商行","甘肃银行"]