	port="8080"
	[jwt]
		realm="atlasmap"
		key="salta-atad-6221"
		timeOut="720h"
		timeMax="72000h"
		identityKey="id"
		lookup="header:Authorization, query:token, cookie:Token"
		headName="Bearer"

	[attempts]
		ip = 50
		user = 7
		expiration = "-5m"

	[db]
		host     = "127.0.0.1"
		port     = "5432"
		user     = "atlas"
		password = "atlas"
		name   = "lzyh"
		
	[models]
		[models.m1]

		[models.m2]
		fields = ["营业面积","人数","个人增长","个人存量","公司存量"]
		scales = [-0.002053894,-0.096727472,0.000316533,4.84E-05,6.37E-06]
		const = 69

		[models.m3]
		field = "类型"
		values = ["1","2","3"]
		basevalues = ["11","22","33"]

		[models.m4] 
		types = ["兰州银行","工商银行","农业银行","中国银行","建设银行","甘肃银行","中信银行","浙商银行","招商银行","邮储银行","交通银行","兴业银行","浦发银行","民生银行","华夏银行","光大银行","榆中农信社","永登农信社","兰州农商行","皋兰农信社","村镇银行"] 
		scales = [1.0,0.45,0.25,0.7,0.45,1.14,0.4,0.4,0.4,0.4,0.4,0.4,0.4,0.4,0.4,0.4,0.4,0.4,0.35,0.4,0.1]