	port="8080"
	[jwt]
		realm="atlasmap"
		key="salta-atad-6221"
		timeOut="720h"
		timeMax="72000h"
		identityKey="id"
		lookup="header:Authorization, query:token, cookie:Token"
		headName="Bearer"

	[attempts]
		ip = 50
		user = 7
		expiration = "-5m"

	[db]
		host     = "127.0.0.1"
		port     = "5432"
		user     = "atlas"
		password = "atlas"
		name   = "atlas"
		
	[buffers]
		static = "static_buffers"
		prefix = "block_"
		suffix = "_buffers"
		scales = "buffer_scales"
		scaleType = "网点类型"
		blocks = "block_lines"


	[models]
		const = 69