	[app]
		port="1226"
		ips = 127
		ipExpiration = "-1m"

	[user]
		resetExpiration = "24h"
		attempts = 7
		attemptExpiration = "-5m"
		verification = true
		
	[paths]
		styles = "styles"
		fonts = "fonts"
		tilesets = "tilesets"
		datasets = "datasets"
		uploads = "tmp"

	[statics]
		home = "statics/"
		templates = "statics/templates/*"

	[db]
		host     = "127.0.0.1"
		port     = 5432
		user     = "atlas"
		password = "atlas"
		database   = "atlas"
	# data providers
	[[providers]]
		name = "atlas"           # provider name is referenced from map layers
		type = "postgis"        # the type of data provider. currently only supports postgis
		host = "127.0.0.1"      # postgis database host
		port = 5432             # postgis database port
		database = "atlas"       # postgis database name
		user = "atlas"         # postgis database user
		password = "atlas"           # postgis database password
		srid = 4326   

	[jwt]
	[jwt.auth]
		realm="atlascloud-auth"
		key="salta-atad-6221"
		timeOut="24h"
		timeMax="72h"
		lookup="header:Authorization, cookie:token"
		headName = "Bearer"

	[jwt.access]
		realm="atlascloud-access"
		key="salta-atad-1226"
		timeOut="65535h"
		timeMax="655350h"
		lookup="query:access_token"
		headName = "Bearer"
		
	[smtp]
		[smtp.from]
			name = "atlascloud"
			address = "cloud@atlasdata.cn"

		[smtp.credentials]
			user = "cloud@atlasdata.cn"
			password = "Atlas1226"
			host = "smtp.exmail.qq.com"
			port = 465
			ssl = true

	[import]
	[import.task]
		interval = "1s"
