	[app]
		port="1226"
		ips = 127
		ipExpiration = "-1m"

	[user]
		resetExpiration = "48h"
		attempts = 7
		attemptExpiration = "-5m"
		verification = true
		
	[paths]
		styles = "styles"
		fonts = "fonts"
		tilesets = "tilesets"
		datasets = "datasets"
		uploads = "tmp"

	[statics]
		home = "statics/"
		templates = "statics/templates/*"

	[db]
		name = "atlas"           
		type = "sqlite3"        # sqlite3,postgres
		host     = "127.0.0.1"
		port     = 5432
		user     = "postgres"
		password = "atlas"
		sysdb = "dev"
		datadb = "devdata"
	# data providers
	[[providers]]
		name = "atlas"           # provider name is referenced from map layers
		type = "gpkg"        # postgis,gpkg 
		filepath = "devdata"
		host = "127.0.0.1"      # postgis database host
		port = 5432             # postgis database port
		user = "postgres"         # postgis database user
		password = "atlas"           # postgis database password
		database = "devdata"       # postgis database name
		srid = 4326 #默认目标是3857，原始数据层可以是3857但通常是4326   

	[jwt]
	[jwt.auth]
		realm="atlascloud-auth"
		key="salta-atad-6221"
		timeOut="24h"
		timeMax="72h"
		lookup="header:Authorization, cookie:token"
		headName = "Bearer"

	[jwt.access]
		realm="atlascloud-access"
		key="salta-atad-1226"
		timeOut="65535h"
		timeMax="655350h"
		lookup="query:access_token"
		headName = "Bearer"
		
	[smtp]
		[smtp.from]
			name = "atlascloud"
			address = "cloud@atlasdata.cn"

		[smtp.credentials]
			user = "cloud@atlasdata.cn"
			password = "Atlas1226"
			host = "smtp.exmail.qq.com"
			port = 465
			ssl = true

	[import]
	[import.task]
		interval = "1s"

	[tree]
		tables = ["districts","streets"]
		tableids = ["9k5vgLHWg","FH8GRYHWg"]
		level0s = ["市本级","区本级"]
	[list]
		tables = ["roads","houses","buildings"]
		tableids = ["86jAMx7ZR","jwO1GxnZR","GNifGxnZR"]
		selectfields = ["","",""]
	[search]
		tables = ["roads","houses","buildings"]
		tableids = ["86jAMx7ZR","jwO1GxnZR","GNifGxnZR"]
		fields = ["name,districts","name,districts","name,districts"]
		matchfields = ["name","name","name"]
		selectfields = ["","",""]
		typenames = ["道路街巷","城镇居民点","建筑物"]
	[attachment]
		path = "redfiles"
