# register data providers
[[providers]]
name = "osm"           # provider name is referenced from map layers
type = "postgis"        # the type of data provider. currently only supports postgis
host = "localhost"      # postgis database host
port = 5432             # postgis database port
database = "postgis24"       # postgis database name
user = "postgres"         # postgis database user
password = "postgres"           # postgis database password
srid = 4326    
  [[providers.layers]]
  name = "places_a"
  tablename="osm_places_a"